### PR TITLE
Remove unneeded dev dep.

### PR DESCRIPTION
**Pull request by jdalton**
This PR removes an unneeded dev dep.

### CODE REVIEW

**Comment by jdalton** [comment]
Ping.

**Comment by jdalton** [comment]
Ping.

**Comment by jdalton** [comment]
Ping.

**Comment by Paxa** [comment]
Would be nice to get it merged

**Comment by jaylinski** [comment]
+1

**Comment by chase-manning** [comment]
Thanks so much for creating this PR!!  
Sorry this never got merged, I have created a new PR #138 which implements this change.  
I would merge this PR but it has a merge conflict.

**Comment by jaylinski** [comment]
Better late then never :sweat_smile:

**Pull request closed without merging**
