### PR TITLE
Update devDep, switch to esm, require node 12.20

### PR DESCRIPTION
**Pull request by jimmywarting**

### CODE REVIEW

**Comment by chase-manning** [comment]
@jimmywarting  Oh dude so nice! You're making this house a home!

**Comment by jimmywarting** [comment]
Glad I can help, trying out smaller PR b/c they can be easier to review

**Comment by Vogel612** [comment]
Switching to ESM is a breaking change for consumers that are still on CJS, that IMO should have been clearly indicated in the release notes.

I agree with the move, I'm just... annoyed that it was not mentioned in the release notes... @chase-manning

**Comment by chase-manning** [comment]
@Vogel612  It was mentioned in the release notes here: https://github.com/felixge/node-dateformat/releases/tag/v5.0.1

**Comment by Vogel612** [comment]
That description makes it look like an import format change, not a bundling change. At least I did not read that as a switch to ESM (which also happened in 4.6.1 and not 5.0.1)...

**Pull request merged**
