### PR TITLE
Adding padding to week (W)

### PR DESCRIPTION
**Pull request by smithalexk**
Creating a WW option which adds padding to weeks for weeks < 10

### CODE REVIEW

**Comment by chase-manning** [comment]
@smithalexk  Great idea! 

Would you be able to please make a couple of inclusions in this PR?  
Adding documentation for the `WW` mask to the Readme would be awesome!  
And also if you could please add some tests to cover this 😄

**Comment by smithalexk** [comment]
Hi @chase-manning  yep will do! Sorry! I set this up quickly in a dependency of another extension, saw it worked, and decided to set up a PR for it. I'll get everything set up soon!

**Comment by smithalexk** [comment]
Ok, the tests are added (and passing), and the README has been updated 😄

**Comment by chase-manning** [comment]
@smithalexk Awesome job! Thanks heaps for the contribution 😄   
Merging now and will publish a package update.

**Pull request merged**
