### PR TITLE
Pinned versions of get-stdin and meow so for compatibility with older…

### LINKED ISSUE #32: Stick version of get-stdin
A new major version of [`get-stdin`](https://www.npmjs.com/package/get-stdin) has been published yesterday (v5.0.0).
It now uses native promises. So, it does not support Node 0.10.x anymore.

Would it be possible to stick the dependency at `^0.4.1`?

### PR DESCRIPTION
**Pull request by robinj**
… versions of node fixes #32

### CODE REVIEW

**Comment by connesc** [comment]
Allowing minor updates could be more appropriate here (note the `^`):
```javascript
{
    "get-stdin": "^4.0.1",
    "meow": "^3.3.0"
}
```

**Comment by robinj** [comment]
I agree, assuming that the modules are using semver properly (which they seem to be), your suggestion makes more sense. I have updated accordingly.

**Comment by mwoc** [comment]
+1

**Comment by watson** [comment]
@felixge I was just about to create the same PR - but someone already beat me too it +1. Hope to see this released soon :smiley:

**Comment by felixge** [comment]
17364d40e61c06f6de228ab94f3660a27f357f01

**Pull request merged**
