### PR TITLE
removes CLI

### PR DESCRIPTION
**Pull request by jonschlinkert**
Related to https://github.com/felixge/node-dateformat/issues/36. 

Thanks! (and sorry for taking so long)

### CODE REVIEW

**Comment by phated** [comment]
As per https://github.com/felixge/node-dateformat/issues/36#issuecomment-226994264 - ping @felixge

**Comment by jonschlinkert** [comment]
thanks @phated, good memory!

**Comment by felixge** [comment]
This breaks bin/cli.js. Please fix it or remove it as well.

**Comment by jonschlinkert** [comment]
No problem, I thought that was removed. will do it now

**Comment by felixge** [comment]
@jonschlinkert LGTM. What's your npm user name? I'll add you as a repo contributor and npm owner so you can publish this change yourself.

**Comment by jonschlinkert** [comment]
great, thanks! it's the same, `jonschlinkert`

**Comment by jonschlinkert** [comment]
@felixge ping, just a reminder to add me to npm, thx!

**Comment by felixge** [comment]
@jonschlinkert done. sorry for delay

**Comment by jonschlinkert** [comment]
thanks! much appreciated.

**Comment by MarkHerhold** [comment]
@jonschlinkert Did you manage to get the access you need for this?

**Comment by jonschlinkert** [comment]
@MarkHerhold yes. however, I'd like some feedback before I do this. 

The main issue I'm hoping to resolve is that every install of gulp comes with ~48 extra deps that don't do anything at all but take up space. This is not the end of the world by any means, but removing these could make installations that much faster. 

To get to the point, if I publish this as a major (which I would normally do), the problem I'm hoping to solve won't be solved - unless we can bump this in gulp-util as well, which is locked afaik. 

@phated would you be willing to make an exception and bump this one module in gulp-util? Or do you have a suggestion on how we can do this so that dateformat gets a proper bump, and we also remove these extra deps from gulp-util?

**Comment by phated** [comment]
Yeah, I can bump it.

**Comment by tunnckoCore** [comment]
Yea, let's create `datetime-cli` for that thing.

**Comment by jonschlinkert** [comment]
awesome! I'll do this tonight. @phated want me to do a pr to bump, or do you want to do it? thanks, I really appreciate it.

**Comment by jonschlinkert** [comment]
@felixge looks like I don't have write access to the repo, so I can't merge.

**Comment by MarkHerhold** [comment]
@jonschlinkert Do we also want to squeeze in #40? Just being opportunistic... ;)

**Comment by jonschlinkert** [comment]
@MarkHerhold that makes sense. If we're going to do a major, that looks like low-hanging fruit. Although I should quell any more opportunism by saying that I won't have much more time to review other prs atm.

**Comment by MarkHerhold** [comment]
@jonschlinkert fine by me!

**Comment by phated** [comment]
@jonschlinkert feel free to submit a PR on gulp-util

**Comment by jonschlinkert** [comment]
no prob, once we get this resolved I'll create a pr, thx

**Comment by alexindigo** [comment]
@jonschlinkert Just curious where things stand. Thanks.

**Comment by jonschlinkert** [comment]
> looks like I don't have write access to the repo, so I can't merge.

@felixge ping

**Comment by felixge** [comment]
@jonschlinkert added you. If you give me your NPM user handle, I'll add you there as well.

**Comment by jonschlinkert** [comment]
thanks! my username is `jonschlinkert` on npm

**Comment by felixge** [comment]
@jonschlinkert added you on npm as well.

**Comment by doowb** [comment]
> if I publish this as a major (which I would normally do)

Since the cli was added as a patch bump, I think this should just be a patch bump. Also, the module's api hasn't changed (which is the main use case). I think it'll save other people's time too, since they won't have to explicitly update anything.

**Comment by jonschlinkert** [comment]
> Since the cli was added as a patch bump

I agree. I've had time to think about this, and since this is CLI-related it's not going to break any production applications if we do a patch bump. Meaning even if someone is using the CLI, they wouldn't even notice it was removed until they had to (manually) reinstall it globally - at which point they can just as easily install date-format-cli.  Plus if we did that then gulp-util wouldn't need to be updated either.  

Unless I get any objections I'm inclined to agree with @doowb.

@felixge @phated?

**Comment by phated** [comment]
I disagree.  People could be using the bin through npm scripts hoisting.

**Comment by jonschlinkert** [comment]
> I disagree.

ah, meaning installing locally and using the CLI. Reminds me of why I suggested a major before. ok I'll still go with the plan to bump the major then do a pr on gulp-util. 

I'll do this ASAP, I'm (still) wrapping up a prior commitment that has been pretty time consuming this past week. sorry for the delay

**Comment by tunnckoCore** [comment]
> I disagree.

Me too. Removing means breaking in almost 99% of the cases, imo. I added it in patch version, cuz it really does not have matter when adding and no breaking changes.

**Comment by MarkHerhold** [comment]
@jonschlinkert I think we have a consensus to cut a major version. Can we please make a cut get this published?

**Pull request merged**
