### PR TITLE
Adding `p` as timezone offset, e.g. `+02:00`

### PR DESCRIPTION
**Pull request by fboes**
Because the feed validator for ATOM complains about timezone offset being given as `+0200` and not as `+02:00`, I added a slight modification of the `o` and called it `p` (like in [PHP's date function](http://php.net/manual/de/function.date.php)).

Cheers & thanks for this great lib,
Frank

closes: #148

### CODE REVIEW

**Comment by axelson** [comment]
Looking forward to being able to use this directly! Is there a workaround to use until this lands?

**Comment by fboes** [comment]
Something like this:

```javascript
dateFormat(date, 'isoDateTime').replace(/(\d{2})(\d{2})$/, '$1:$2');
```

**Comment by jheander** [comment]
As an interrim solution, fixed in https://www.npmjs.com/package/dateformat-light/v/1.3.0

**Comment by fboes** [comment]
As the original solution is more than 2 years old, I changed it to be mergable to the current official state.

**Comment by chase-manning** [comment]
@fboes Thanks so much for creating this PR!!! This is such a good idea :smile:  
Sorry this was not merged earlier, this repo was not under active maintenance at the time.  
I would love to merge this now but there are currently some merge conflicts.  
Would you be able to please fix these merge conflicts and then I will happily merge this!

**Comment by fboes** [comment]
Because the merge conflicts were to complicated, I build a completely new solution in https://github.com/felixge/node-dateformat/pull/149. Please disregard this pull request. ;)

**Pull request closed without merging**
